name: 'Docker Run Action'
description: 'Run a command in a new container'
inputs:
  tag:
    description: 'The tag of the image to run.'
    required: true
  run:
    description: 'Run command in container'
    required: true
  target:
    description: 'Docker target to run (development|production)'
    required: false
    default: 'production'

runs:
  using: 'composite'
  steps:
    - name: Up
      id: run
      shell: bash
      run: |
        make up \
          DOCKER_TAG="${{ inputs.tag }}" \
          DOCKER_TARGET="${{ inputs.target }}" \
          DOCKER_PORT="80"

        cat <<'EOF' | docker compose exec --user nodeuser web bash
          ${{ inputs.run }}
        EOF
