name: Docker Tag
description: Tag a Docker image

inputs:
  tag:
    description: The full docker tag to use
    required: true

outputs:
  tag:
    description: The full docker tag to use
    value: ${{ steps.tag.outputs.DOCKER_TAG }}
  registry:
    description: The registry to tag the image with
    value: ${{ steps.tag.outputs.DOCKER_REGISTRY }}
  image:
    description: The image to tag
    value: ${{ steps.tag.outputs.DOCKER_IMAGE }}
  version:
    description: The version to tag the image with
    value: ${{ steps.tag.outputs.DOCKER_VERSION }}
  digest:
    description: The digest to tag the image with
    value: ${{ steps.tag.outputs.DOCKER_DIGEST }}
  target:
    description: The target to tag the image with
    value: ${{ steps.tag.outputs.DOCKER_TARGET }}
  node_env:
    description: The node environment to tag the image with
    value: ${{ steps.tag.outputs.NODE_ENV }}

runs:
  using: composite
  steps:
    - name: Extract tag
      id: tag
      shell: bash
      run: |
        make env DOCKER_TAG="${{ inputs.tag }}"
        echo "$(cat .env)" >> "$GITHUB_OUTPUT"
        rm -f .env
