services:
  web:
    image: "${WEB_DOCKER_TAG:-kevin-mind/nopo-web:local}"
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET:-development}
      args:
        NODE_ENV: ${NODE_ENV:-development}
        APP_NAME: "@more/web"
      cache_from:
        - "type=gha"
      cache_to:
        - "type=gha,mode=max"
    volumes:
      - ./:/app
      # - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV
      - DATABASE_URL
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=website
      - POSTGRES_USER=website
      - POSTGRES_PASSWORD=website
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
