services:
  web:
    extends:
      file: packages/docker/docker-compose.base.yml
      service: base
    image: "${WEB_DOCKER_TAG:-kevinmind/website:local}"
    build:
      args:
        - APP_NAME=web
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV
      - DATABASE_URL
    ports:
      - "${WEB_DOCKER_PORT}:${WEB_DOCKER_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WEB_DOCKER_PORT}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
