services:
  base:
    extends:
      file: docker/docker-compose.base.yml
      service: base_builder
    command:
      - /sync-host.sh
    volumes:
      - ./docker/sync-host.sh:/sync-host.sh

  web:
    extends:
      file: docker/docker-compose.base.yml
      service: base_service
    environment:
      SERVICE_NAME: web
      SERVICE_PORT: 3000
      SERVICE_PUBLIC_PATH: /web
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy

  backend:
    extends:
      file: docker/docker-compose.base.yml
      service: base_service
    environment:
      SERVICE_NAME: backend
      SERVICE_PORT: 8000
      SERVICE_PUBLIC_PATH: /api
    ports:
      - 8000:8000

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: website
      POSTGRES_USER: website
      POSTGRES_PASSWORD: website
    ports:
      - "5432:5432"
    volumes:
      - data_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U website -d website']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx:/etc/nginx/templates
    environment:
      # Web configuration
      SERVICE_WEB_PORT: 3000
      SERVICE_WEB_PUBLIC_PATH: /web
      SERVICE_WEB_NAME: web
      # Backend configuration
      SERVICE_BACKEND_PORT: 8000
      SERVICE_BACKEND_PUBLIC_PATH: /api
      SERVICE_BACKEND_NAME: backend
    ports:
      - "8080:80"
    networks:
      default:
    depends_on:
      - web
      - backend

networks:
  default:
    driver: bridge
    enable_ipv6: false

volumes:
  data_postgres:
