services:
  base:
    extends:
      file: docker/docker-compose.base.yml
      service: base_builder
    command:
      - /sync-host.sh
    volumes:
      - ./docker/sync-host.sh:/sync-host.sh

  web:
    extends:
      file: docker/docker-compose.base.yml
      service: base_service
    environment:
      SERVICE_NAME: web
      PORT: 80
      SERVICE_PUBLIC_PATH: /
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      db:
        condition: service_healthy

  backend:
    extends:
      file: docker/docker-compose.base.yml
      service: base_service
    environment:
      SERVICE_NAME: backend
      SERVICE_PUBLIC_PATH: /api
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: website
      POSTGRES_USER: website
      POSTGRES_PASSWORD: website
    volumes:
      - data_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U website -d website']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx:/etc/nginx/templates
    ports:
      - "${DOCKER_PORT:?}:80"
    networks:
      default:
    depends_on:
      - web
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  default:
    driver: bridge
    enable_ipv6: false

volumes:
  data_postgres:
