services:
  base:
    image: "${DOCKER_TAG:-kevin-mind/nopo:local}"
    build: {}
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV

  base_service:
    extends:
      service: base
    restart: always
    depends_on:
      base:
        condition: service_completed_successfully
