services:
  base:
    image: "${DOCKER_TAG:?}"
    user: root
    env_file:
      - path: ../.env
        required: false
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: ${DOCKER_TARGET:?}
      args:
        NODE_ENV: ${NODE_ENV:?}
        DOCKER_TAG: ${DOCKER_TAG:?}
        DOCKER_VERSION: ${DOCKER_VERSION:?}
        DOCKER_TARGET: ${DOCKER_TARGET:?}
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
    volumes:
      - ..:/app:cached
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV
      - HOST_UID

  base_service:
    extends: base
    restart: always
    depends_on:
      base:
        condition: service_completed_successfully
