services:
  base:
    image: "${DOCKER_TAG:?}"
    pull_policy: never
    volumes:
      - ..:/app:cached
      - ../.venv:/app/.venv:cached
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI
