services:
  base:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        NODE_ENV: "${NODE_ENV}"
        DOCKER_TARGET: "${DOCKER_TARGET}"
        DOCKER_TAG: "${DOCKER_TAG}"
        DOCKER_VERSION: "${DOCKER_VERSION}"
        GIT_REPO: "${GIT_REPO}"
        GIT_BRANCH: "${GIT_BRANCH}"
        GIT_COMMIT: "${GIT_COMMIT}"
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
      pull: true
      target: "${DOCKER_TARGET}"
