services:
  base:
    image: "${DOCKER_TAG:?}"
    user: root
    entrypoint: ["/entrypoint.sh"]
    env_file:
      - path: ../.env
        required: false
    platform: linux/amd64
    volumes:
      - ..:/app:cached
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV
      - HOST_UID

  base_service:
    extends: base
    restart: always
    depends_on:
      base:
        condition: service_completed_successfully
