name: Context
description: Log context about a workflow run

outputs:
  is_fork:
    description: 'Whether the repository is a fork'
    value: ${{ steps.context.outputs.is_fork }}
  default_branch:
    description: 'The default branch of the repository'
    value: ${{ steps.context.outputs.default_branch }}

runs:
  using: composite
  steps:
    - name: Github
      shell: bash
      run: |
        cat <<EOF
        ${{ toJSON(github) }}
        EOF

    - name: Job
      shell: bash
      run: |
        cat <<EOF
        ${{ toJSON(job) }}
        EOF

    - name: Context
      id: context
      shell: bash
      env:
        default_branch: ${{ github.event.repository.default_branch }}
        is_fork: ${{ github.event.repository.fork }}
      run: |
        echo "default_branch=$default_branch" >> "$GITHUB_OUTPUT"
        echo "is_fork=$is_fork" >> "$GITHUB_OUTPUT"
        cat "$GITHUB_OUTPUT"
