name: Context
description: Log context about a workflow run

runs:
  using: composite
  steps:
    - name: Github
      shell: bash
      run: |
        cat <<EOF
        ${{ toJSON(github) }}
        EOF

    - name: Job
      shell: bash
      run: |
        cat <<EOF
        ${{ toJSON(job) }}
        EOF

