name: Setup Docker
description: Setup Docker/Buildx

inputs:
  registry:
    description: 'Docker registry'
    required: true
  username:
    description: 'Docker username'
    required: false
  password:
    description: 'Docker password'
    required: false

outputs:
  builder:
    description: 'Docker Buildx builder'
    value: ${{ steps.buildx.outputs.name }}
runs:
  using: composite
  steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
