name: Build

on:
  workflow_call:
    inputs:
      push:
        description: 'Whether to push the image'
        required: true
        type: boolean

    outputs:
      registry:
        description: 'The registry of the build'
        value: ${{ jobs.build.outputs.registry }}
      image:
        description: 'The image of the build'
        value: ${{ jobs.build.outputs.image }}
      version:
        description: 'The version of the build'
        value: ${{ jobs.build.outputs.version }}
      digest:
        description: 'The digest of the build'
        value: ${{ jobs.build.outputs.digest }}
      tag:
        description: 'The tag of the build'
        value: ${{ jobs.build.outputs.tag }}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.output_tag.outputs.registry }}
      image: ${{ steps.output_tag.outputs.image }}
      version: ${{ steps.output_tag.outputs.version }}
      digest: ${{ steps.output_tag.outputs.digest }}
      tag: ${{ steps.output_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          bake-target: default
          tags: |
            type=sha

      - name: Input tag
        id: input_tag
        uses: ./.github/actions/docker-tag
        with:
          registry: ghcr.io
          image: ${{ github.repository }}
          version: ${{ steps.docker_meta.outputs.version }}

      - name: Set up Docker
        id: docker
        uses: ./.github/actions/setup-docker

      - name: Build
        id: build
        env:
          DOCKER_BUILDER: ${{ steps.docker.outputs.builder }}
          DOCKER_TAG: ${{ steps.input_tag.outputs.tag }}
          DOCKER_BUILD: ${{ format('{0}/actions/runs/{1}', github.event.repository.html_url, github.run_id) }}
          push: ${{ inputs.push }}
        run: |
          make image \
            DOCKER_BUILDER=${DOCKER_BUILDER} \
            DOCKER_TAG=${DOCKER_TAG} \
            DOCKER_BUILD=${DOCKER_BUILD}

      - name: Login to Docker registry
        if: ${{ inputs.push }}
        uses: ./.github/actions/login-docker
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        if: ${{ inputs.push }}
        env:
          tag: ${{ steps.input_tag.outputs.tag }}
        run: |
          docker push $tag

      - name: Extract build digest
        id: digest
        env:
          push: ${{ inputs.push }}
          tag: ${{ steps.input_tag.outputs.tag }}
        run: |
          digest=$(docker inspect $tag | jq -r '.[0].RepoDigests')

          if [[ "$push" == "true" && "$digest" != "[]" ]]; then
            digest=$(echo "$digest" | jq -r '.[0]' | cut -d '@' -f 2)
          else
            digest=""
          fi

          echo "digest=$digest" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

      - name: Output tag
        id: output_tag
        uses: ./.github/actions/docker-tag
        with:
          registry: ${{ steps.input_tag.outputs.registry }}
          image: ${{ steps.input_tag.outputs.image }}
          version: ${{ steps.input_tag.outputs.version }}
          # Add the digest to the output tag so we can easily pull the exact build later.
          digest: ${{ inputs.push && steps.digest.outputs.digest || '' }}
