name: Build
description: Build the image and optionally push it to ghcr.io

on:
  workflow_call:
    inputs:
      push:
        description: 'Whether to push the image'
        required: true
        type: boolean

    outputs:
      registry:
        description: 'The registry of the build'
        value: ${{ jobs.build.outputs.registry }}
      image:
        description: 'The image of the build'
        value: ${{ jobs.build.outputs.image }}
      version:
        description: 'The version of the build'
        value: ${{ jobs.build.outputs.version }}
      digest:
        description: 'The digest of the build'
        value: ${{ jobs.build.outputs.digest }}
      tag:
        description: 'The tag of the build'
        value: ${{ jobs.build.outputs.tag }}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.docker_tag.outputs.registry }}
      image: ${{ steps.docker_tag.outputs.image }}
      version: ${{ steps.docker_tag.outputs.version }}
      digest: ${{ steps.digest.outputs.digest }}
      # Append the build digest to the tag so we can easily pull the exact build later.
      tag: "${{ steps.docker_tag.outputs.tag }}@${{ steps.digest.outputs.digest }}"
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          bake-target: default
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Docker tag
        id: docker_tag
        uses: ./.github/actions/docker-tag
        with:
          registry: 'ghcr.io'
          image: ${{ github.repository }}
          version: ${{ steps.docker_meta.outputs.version }}
          docker_target: production
          node_env: production

      - name: Set up Docker
        id: docker
        uses: ./.github/actions/setup-docker

      - name: Login to Docker registry
        uses: ./.github/actions/login-docker
        with:
          registry: ${{ steps.docker_tag.outputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: build
        uses: docker/bake-action@v6
        env:
          DOCKER_REGISTRY: ${{ steps.docker_tag.outputs.registry }}
          DOCKER_IMAGE: ${{ steps.docker_tag.outputs.image }}
          DOCKER_VERSION: ${{ steps.docker_tag.outputs.version }}
          DOCKER_TARGET: ${{ steps.docker_tag.outputs.docker_target }}
          NODE_ENV: ${{ steps.docker_tag.outputs.node_env }}
        with:
          builder: ${{ steps.docker.outputs.builder }}
          files: |
            docker-bake.hcl
            cwd://${{ steps.docker_meta.outputs.bake-file-tags }}
            cwd://${{ steps.docker_meta.outputs.bake-file-labels }}
          push: ${{ inputs.push }}

      - name: Extract build digest
        id: digest
        run: |
          cat <<EOF > metadata.json
          ${{ steps.build.outputs.metadata }}
          EOF
          digest=$(cat metadata.json | jq -r '.base["containerimage.digest"]')
          echo "digest=$digest" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
