name: Build and Push

on:
  workflow_call:
    inputs:
      registry:
        description: 'The registry to use for the build'
        required: true
        type: string
      image:
        description: 'The image to build and push'
        required: true
        type: string
      username:
        description: 'The username to use for the build'
        required: true
        type: string

    secrets:
      password:
        description: 'The password to use for the build'
        required: true

    outputs:
      registry:
        description: 'The registry used for the build'
        value: ${{ inputs.registry }}
      image:
        description: 'The image used for the build'
        value: ${{ inputs.image }}
      version:
        description: 'The version used for the build'
        value: ${{ jobs.build.outputs.version }}
      digest:
        description: 'The digest of the build'
        value: ${{ jobs.build.outputs.digest }}
      tag:
        description: 'The tag of the build'
        value: ${{ jobs.build.outputs.tag }}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.post.outputs.version }}
      digest: ${{ steps.post.outputs.digest }}
      tag: ${{ steps.post.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          bake-target: default
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.password }}

      - name: Build and push
        id: build
        uses: docker/bake-action@v6
        env:
          NODE_ENV: production
          DOCKER_REGISTRY: ${{ inputs.registry }}
          DOCKER_IMAGE: ${{ inputs.image }}
          DOCKER_VERSION: ${{ steps.meta.outputs.version }}
          DOCKER_TARGET: production
        with:
          builder: ${{ steps.buildx.outputs.name }}
          files: |
            docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file-tags }}
            cwd://${{ steps.meta.outputs.bake-file-labels }}
          push: true

      - name: Write metadata
        id: post
        run: |
          cat <<EOF > metadata.json
          ${{ steps.build.outputs.metadata }}
          EOF

      - name: Upload metadata
        uses: actions/upload-artifact@v4
        with:
          name: build-metadata
          path: metadata.json
