name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to deploy'
        required: true
        type: string
      digest:
        description: 'The digest to deploy'
        required: false
        type: string
      environment:
        description: 'The environment to deploy to'
        required: true
        type: choice
        options:
          - stage
          - prod

  workflow_call:
    inputs:
      version:
        description: 'The version to deploy'
        required: true
        type: string
      digest:
        description: 'The digest to deploy'
        required: false
        type: string
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string

permissions: {}

defaults:
  run:
    shell: bash

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      app_names: ${{ steps.app_names.outputs.app_names }}
    steps:
      - uses: actions/checkout@v4

      - name: Set App Names
        id: app_names
        env:
          environment: ${{ inputs.environment }}
        run: |
          app_names=$(
            ls "docker/fly/nopo-${environment}"-*.toml \
              | xargs -n 1 basename \
              | sed 's/\.toml$//' \
              | sort -u \
              | jq -R . \
              | jq -s . \
              | jq -c .
          )

          echo "app_names=${app_names}" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  pre_approve:
    name: Pre-Approve deployments for (${{ needs.context.outputs.app_names }})
    needs: [context]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      pull_tag: ${{ steps.pull_tag.outputs.tag }}
      rollback_version: ${{ steps.rollback_version.outputs.version }}
      pull_version: ${{ steps.pull_tag.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/setup-docker
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Tag
        id: pull_tag
        uses: ./.github/actions/docker-tag
        with:
          registry: ghcr.io
          image: ${{ github.repository }}
          version: ${{ inputs.version }}
          digest: ${{ inputs.digest }}

      - name: Rollback Tag
        id: rollback_tag
        uses: ./.github/actions/docker-tag
        with:
          registry: ghcr.io
          image: ${{ github.repository }}
          version: latest

      - name: Get Rollback Version
        id: rollback_version
        shell: bash
        env:
          pull_tag: ${{ steps.rollback_tag.outputs.tag }}
        run: |
          docker pull "${pull_tag}"
          version=$(docker run --rm "${pull_tag}" cat /build-info.json | jq -r '.version')
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: [context, pre_approve]
    timeout-minutes: 10
    concurrency:
      group: deploy-job-${{ matrix.app_name }}
    strategy:
      matrix:
        app_name: ${{ fromJson(needs.context.outputs.app_names) }}
    outputs:
      deployed: ${{ steps.deploy.outcome == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/setup-docker
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Tag
        id: push_tag
        uses: ./.github/actions/docker-tag
        with:
          registry: registry.fly.io
          image: ${{ matrix.app_name }}
          version: ${{ needs.pre_approve.outputs.pull_version }}

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Login to Fly
        run: flyctl auth docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Push image
        env:
          pull_tag: ${{ needs.pre_approve.outputs.pull_tag }}
          push_tag: ${{ steps.push_tag.outputs.tag }}
        run: |
          docker pull "${pull_tag}"
          docker tag "${pull_tag}" "${push_tag}"
          docker push "${push_tag}"

      - name: Deploy to Fly
        id: deploy
        uses: ./.github/actions/deploy
        with:
          token: ${{ secrets.FLY_API_TOKEN }}
          image: ${{ steps.push_tag.outputs.tag }}
          app_name: ${{ matrix.app_name }}
          version: ${{ steps.push_tag.outputs.version }}

  deploy_nginx:
    runs-on: ubuntu-latest
    needs: [context, deploy]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Nginx
        id: deploy_nginx
        uses: ./.github/actions/deploy-nginx
        with:
          token: ${{ secrets.FLY_API_TOKEN }}
          apps: ${{ needs.context.outputs.app_names }}
          environment: ${{ inputs.environment }}

      - name: Smoke test
        uses: ./.github/actions/smoketest
        with:
          public_url: ${{ steps.deploy_nginx.outputs.public_url }}

  post_approve:
    name: Post-Approve deployments for (${{ needs.context.outputs.app_names }})
    if: |
      always() &&
      needs.deploy.result == 'success' &&
      needs.deploy_nginx.result == 'success'
    needs: [context, deploy, deploy_nginx]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Wait for approval
        run: echo "Waiting for approval"

  rollback:
    if: |
      always() &&
      needs.pre_approve.outputs.rollback_version != '' &&
      needs.deploy.outputs.deployed == 'true' &&
      (needs.deploy.result != 'success'|| needs.post_approve.result != 'success')
    name: Rollback
    needs: [context, pre_approve, deploy, deploy_nginx, post_approve]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        app_name: ${{ fromJson(needs.context.outputs.app_names) }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Rollback Tag
        id: rollback_tag
        uses: ./.github/actions/docker-tag
        with:
          registry: registry.fly.io
          image: ${{ matrix.app_name }}
          version: ${{ needs.pre_approve.outputs.rollback_version }}

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Rollback
        id: rollback
        uses: ./.github/actions/deploy
        with:
          token: ${{ secrets.FLY_API_TOKEN }}
          image: ${{ steps.rollback_tag.outputs.tag }}
          app_name: ${{ matrix.app_name }}
          version: ${{ steps.rollback_tag.outputs.version }}



