name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to deploy'
        required: true
        type: string
      digest:
        description: 'The digest to deploy'
        required: false
        type: string
      service:
        description: 'The service to deploy'
        required: true
        type: choice
        options:
          - web
      environment:
        description: 'The environment to deploy to'
        required: true
        type: choice
        options:
          - stage
          - prod

  workflow_call:
    inputs:
      version:
        description: 'The version to deploy'
        required: true
        type: string
      digest:
        description: 'The digest to deploy'
        required: false
        type: string
      service:
        description: 'The service to deploy'
        required: true
        type: string
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string

    outputs:
      deploy_tag:
        description: the tag that was (attempted to be) deployed
        value: ${{ jobs.deploy.outputs.push_tag }}
      rollback:
        description: The JSON output from the /__version__ endpoint of the previous deployment
        value: ${{ jobs.deploy.outputs.rollback_meta }}

permissions: {}

defaults:
  run:
    shell: bash

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: ${{ inputs.environment }}
    outputs:
      pull_tag: ${{ steps.pull_tag.outputs.tag }}
      push_tag: ${{ steps.push_tag.outputs.tag }}
      rollback_meta: ${{ steps.deploy.outputs.rollback_meta }}
      deployed: ${{ steps.deploy.outcome == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/setup-docker
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Tag
        id: pull_tag
        uses: ./.github/actions/docker-tag
        with:
          registry: ghcr.io
          image: ${{ github.repository }}
          version: ${{ inputs.version }}
          digest: ${{ inputs.digest }}

      - name: Push Tag
        id: push_tag
        uses: ./.github/actions/docker-tag
        with:
          registry: registry.fly.io
          image: ${{ vars.APP_NAME }}
          version: ${{ steps.pull_tag.outputs.version }}

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Login to Fly
        run: flyctl auth docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Push image
        env:
          pull_tag: ${{ steps.pull_tag.outputs.tag }}
          push_tag: ${{ steps.push_tag.outputs.tag }}
        run: |
          docker pull "${pull_tag}"
          docker tag "${pull_tag}" "${push_tag}"
          docker push "${push_tag}"

      - name: Deploy to Fly
        id: deploy
        uses: ./.github/actions/deploy
        with:
          token: ${{ secrets.FLY_API_TOKEN }}
          image: ${{ steps.push_tag.outputs.tag }}
          app_public_url: ${{ vars.APP_PUBLIC_URL }}
          app_name: ${{ vars.APP_NAME }}
          version: ${{ steps.push_tag.outputs.version }}
          service: ${{ inputs.service }}

      - name: Run smoke test
        uses: ./.github/actions/smoketest
        with:
          app_public_url: ${{ vars.APP_PUBLIC_URL }}

  approve:
    if: ${{ always() && needs.deploy.result == 'success' }}
    needs: [deploy]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Wait for approval
        run: echo "Waiting for approval"

  rollback:
    if: |
      always() &&
      needs.deploy.outputs.rollback_meta != '' &&
      needs.deploy.outputs.deployed == 'true' &&
      (needs.deploy.result != 'success'|| needs.approve.result != 'success')
    name: Rollback
    needs: [deploy, approve]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Rollback tag
        id: rollback_tag
        uses: ./.github/actions/docker-tag
        with:
          tag: ${{ fromJson(needs.deploy.outputs.rollback_meta).tag }}

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Rollback
        uses: ./.github/actions/deploy
        with:
          token: ${{ secrets.FLY_API_TOKEN }}
          image: ${{ steps.rollback_tag.outputs.tag }}
          version: ${{ steps.rollback_tag.outputs.version }}
          app_public_url: ${{ vars.APP_PUBLIC_URL }}
          app_name: ${{ vars.APP_NAME }}
          service: ${{ inputs.service }}

      - name: Run smoke test
        uses: ./.github/actions/smoketest
        with:
          app_public_url: ${{ vars.APP_PUBLIC_URL }}



