name: Playwright

on:
  workflow_dispatch:
    inputs:
      app_public_url:
        description: 'The public URL of the app'
        required: true
        type: string
      test_pattern:
        description: 'The pattern to test'
        required: true
        type: string
        default: ''

  workflow_call:
    inputs:
      app_public_url:
        description: 'The public URL of the app'
        required: true
        type: string
      test_pattern:
        description: 'The pattern to test'
        required: true
        type: string
        default: ''

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup-node

    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps

    - name: Run Playwright tests
      run: pnpm exec playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
