name: Playwright

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: choice
        options:
          - local
          - stage
          - prod
      tag:
        description: 'The tag to test (only on local environment)'
        required: false
        type: string
      test_pattern:
        description: 'The pattern to test'
        required: false
        type: string
        default: ''

  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      tag:
        description: 'The tag to test (only on local environment)'
        required: false
        type: string
      test_pattern:
        description: 'The pattern to test'
        required: false
        type: string
        default: ''

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v4

    - name: Validate inputs
      env:
        environment: ${{ inputs.environment }}
        tag: ${{ inputs.tag }}
      run: |
        if [[ "${environment}" == "local" ]]; then
          if [[ -z "${tag}" ]]; then
            echo "tag is required when environment is local"
            exit 1
          fi
        else
          if [[ -n "${tag}" ]]; then
            echo "tag is not allowed when environment is not local"
            exit 1
          fi
        fi
    - uses: ./.github/actions/setup-node

    - uses: ./.github/actions/setup-docker

    - name: Make up
      if: ${{ inputs.environment == 'local' }}
      uses: ./.github/actions/run-docker
      with:
        tag: ${{ inputs.tag }}
        target: production
        run: echo "up"

    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps

    - name: Run Playwright tests
      env:
        APP_PUBLIC_URL: ${{ vars.APP_PUBLIC_URL }}
      run: pnpm exec playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
