name: Test
description: Test the docker image either locally or from ghcr.io

on:
  workflow_call:
    inputs:
      tag:
        description: 'The full docker tag to test'
        required: true
        type: string
      registry:
        description: 'The registry to use for the test'
        required: false
        type: string
      username:
        description: 'The username to use for the registry'
        required: false
        type: string
    secrets:
      password:
        description: 'The password to use for the registry'
        required: false

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run:
          - check
          - test
      fail-fast: false
    permissions:
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Docker
        uses: ./.github/actions/setup-docker

      - name: Login Docker
        if: inputs.registry != '' && inputs.username != ''
        uses: ./.github/actions/login-docker
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.password }}

      - name: Up
        run: make up DOCKER_TAG="${{ inputs.tag }}"

      - name: make ${{ matrix.run }}
        run: make ${{ matrix.run }}
