name: Test

on:
  workflow_call:
    inputs:
      registry:
        description: 'The registry to pull the image from'
        required: false
        type: string
        default: null
      username:
        description: 'The username to use for the registry'
        required: false
        type: string
        default: null
    secrets:
      password:
        description: 'The password to use for the registry'
        required: false

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run:
          - check
          - build
    permissions:
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Login to registry
        if: inputs.username != ''
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.password }}

      - name: Up
        run: make up

      - name: Test
        run: docker compose exec web pnpm run ${{ matrix.run }}
