name: Test
description: Test the docker image either locally or from ghcr.io

on:
  workflow_call:
    inputs:
      tag:
        description: 'The full docker tag to test'
        required: true
        type: string
      username:
        description: 'The username to use for the registry'
        required: false
        type: string

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run:
          - check
          - test
      fail-fast: false
    permissions:
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Docker tag
        id: tag
        uses: ./.github/actions/docker-tag
        with:
          tag: ${{ inputs.tag }}

      - name: Set up Docker
        uses: ./.github/actions/setup-docker

      - name: Login Docker
        uses: ./.github/actions/login-docker
        with:
          registry: ${{ steps.tag.outputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Up
        run: make up DOCKER_TAG="${{ steps.tag.outputs.tag }}"

      - name: make ${{ matrix.run }}
        run: make ${{ matrix.run }}
