name: Test

on:
  workflow_call:
    inputs:
      tag:
        description: 'The full docker tag to test'
        required: true
        type: string

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    name: "${{ matrix.service }}: ${{ matrix.command }} (${{ matrix.target }})"
    strategy:
      matrix:
        service: [web, backend]
        command: [check, test]
        target: [development, production]
      fail-fast: false
    permissions:
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Set up Docker
        uses: ./.github/actions/setup-docker
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Tag
        id: docker_tag
        uses: ./.github/actions/docker-tag
        with:
          tag: ${{ inputs.tag }}

      - name: Run '${{ matrix.command }}'
        uses: ./.github/actions/run-docker
        with:
          tag: ${{ steps.docker_tag.outputs.tag }}
          service: ${{ matrix.service }}
          run: make ${{ matrix.command }} DOCKER_SERVICE="${{ matrix.service }}"
          target: ${{ matrix.target }}
