name: CI

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name}}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/context

  build:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    uses: ./.github/workflows/_build-push.yml
    with:
      registry: ghcr.io
      image: ${{ github.repository }}
      username: ${{ github.actor }}
    secrets:
      password: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: build
    permissions:
      packages: read
      contents: read
    uses: ./.github/workflows/_test.yml
    with:
      registry: ${{ needs.build.outputs.registry }}
      username: ${{ github.actor }}
    secrets:
      password: ${{ secrets.GITHUB_TOKEN }}

  deploy_stage:
    needs: test
    if: github.event_name == 'merge_group'
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: stage

  deploy_prod:
    needs: deploy_stage
    if: github.event_name == 'merge_group'
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: prod
