name: CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

env:
  CI: true

jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      is_fork: ${{ steps.context.outputs.is_fork }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Context
        id: context
        uses: ./.github/actions/context

  build:
    needs: [context]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      push: ${{ needs.context.outputs.is_fork == 'false' }}

  test:
    permissions:
      packages: read
      contents: read
    uses: ./.github/workflows/_test.yml
    secrets: inherit
    with:
      tag: local

  smoketest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup-node

    - uses: ./.github/actions/setup-docker

    - name: Make up
      uses: ./.github/actions/run-docker
      with:
        run: echo "up"

    - name: Run smoketest
      uses: ./.github/actions/smoketest
      with:
        public_url: http://localhost

  checks:
    if: always()
    needs: [context, build, test, smoketest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check
        uses: ./.github/actions/check
        with:
          json: ${{ toJson(needs) }}
