name: CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

env:
  CI: true

jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      is_fork: ${{ steps.context.outputs.is_fork }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Context
        id: context
        uses: ./.github/actions/context

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
        with:
          files_yaml: |
            github_actions:
              - .github/**
            backend_migrations:
              - apps/backend/src/*/migrations/**
            backend_source:
              - apps/backend/**
              - "!apps/backend/src/*/migrations/**"

      - name: Debug
        run: |
          cat <<EOF
          ${{ toJson(steps.changed_files.outputs) }}
          EOF

      - name: Fail if migrations and source changed
        if: |
          contains(steps.changed_files.outputs.changed_keys, 'backend_migrations') &&
          contains(steps.changed_files.outputs.changed_keys, 'backend_source')
        run: |
          echo "Migrations and source files cannot be changed together"
          exit 1

  build:
    needs: [context]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      push: ${{ needs.context.outputs.is_fork == 'false' }}

  test:
    needs: [context]
    permissions:
      packages: read
      contents: read
    uses: ./.github/workflows/_test.yml
    secrets: inherit
    with:
      tag: local

  smoketest:
    needs: [context]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup-node

    - uses: ./.github/actions/setup-docker

    - name: Make up
      uses: ./.github/actions/run-docker
      with:
        run: echo "up"

    - name: Run smoketest
      uses: ./.github/actions/smoketest
      with:
        public_url: http://localhost

  checks:
    if: always()
    needs: [context, build, test, smoketest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check
        uses: ./.github/actions/check
        with:
          json: ${{ toJson(needs) }}
