name: CI (complete)

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  complete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/context
