name: CI

on:
  workflow_run:
    workflows: ["Merge Queue"]
    types:
      - completed
      - failed

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  complete:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/context
