name: Merge Queue

on:
  merge_group:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/context

  build:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    uses: ./.github/workflows/_build-push.yml
    with:
      registry: ghcr.io
      image: ${{ github.repository }}-web
      username: ${{ github.actor }}
    secrets:
      password: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: build
    permissions:
      packages: read
      contents: read
    uses: ./.github/workflows/_test.yml
    with:
      tag: ${{ needs.build.outputs.tag }}
      digest: ${{ needs.build.outputs.digest }}

  deploy_stage:
    needs: test
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: stage

  deploy_prod:
    needs: deploy_stage
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: prod
