name: Merge Queue

on:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name}}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      is_fork: ${{ steps.context.outputs.is_fork }}

    steps:
      - id: context
        uses: mozilla/addons-server/.github/actions/context@master

  build:
    needs: context
    if: ${{ needs.context.outputs.is_fork }} == 'false'
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    uses: ./.github/workflows/_build-push.yml
    with:
      registry: ghcr.io
      image: ${{ github.repository }}
      username: ${{ github.actor }}
    secrets:
      password: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: build
    permissions:
      packages: read
      contents: read
    uses: ./.github/workflows/_test.yml
    with:
      tag: ${{ needs.build.outputs.tag }}
      username: ${{ github.actor }}
    secrets:
      password: ${{ secrets.GITHUB_TOKEN }}

  deploy_stage:
    needs: test
    if: github.event_name == 'merge_group'
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: stage

  deploy_prod:
    needs: deploy_stage
    if: github.event_name == 'merge_group'
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: prod
