name: Merge Queue

on:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name}}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      push: true

  test:
    needs: build
    permissions:
      packages: read
      contents: read
    uses: ./.github/workflows/_test.yml
    with:
      tag: ${{ needs.build.outputs.tag }}
    secrets: inherit

  deploy_stage:
    needs: test
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: stage

  deploy_prod:
    needs: deploy_stage
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: prod
