name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name}}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      push: false

  test:
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/_test.yml
    with:
      # We can test PRs using a locally build image.
      # This means forks are tested the same way
      # and build/test can run in parallel.
      tag: local
