name: Pull Request

on:
  pull_request:
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    permissions:
      contents: read
    uses: ./.github/workflows/_test.yml
