name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name}}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/_test.yml
    with:
      tag: local
