name: On Complete (post workflow run)

on:
  workflow_run:
    workflows:
      - Merge Queue
      - Pull Request
    types:
      - completed

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  complete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/context
